import { ISwitcherReportsAndOptions } from '../models/switcherReportsAndOption';

export const switcherGetReportsAndOptions: ISwitcherReportsAndOptions[] = [

  // hdfc normal verdict report
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 2,
        name: 'verdict',
        reason: 'buy and strong buy',
      },
      sname: 'HDFC Bank',
      qty: '',
      mcap: 1230081,
      mcapclass: 'Large Cap',
      ind_name: 'Private Banks',
      mcaptype: 1,
      ind_code: 50,
      verdict: {
        price_info: {
          cmp: 1606.6,
          open_price: 1618.5,
          day_low: 1603.15,
          day_high: 1623.6,
          '52wk_low_dt': '2024-02-14',
          '52wk_high_dt': '2024-07-03',
          altm_low: 3.23,
          altm_high: 1791.9,
          altm_low_dt: '1996-04-11',
          altm_high_dt: '2024-07-03',
          vol_msg: 'Compared to 5 day average volume of 1.78 cr at 15:25 PM',
          mcap_class: 'Large Cap',
          bid_price: 1604.05,
          bid_qty: 456,
          offer_price: 1606.6,
          offer_qty: 11,
          no_of_shares: 7608122302,
          div_yeild: 1.21,
          net_profit: 0,
          pe_ratio: 20.2,
          ind_pe_ratio: '19.4',
          deb_equity: '',
          price_to_book: 2.81,
          net_npa_perc: 0.33,
          gross_npa_perc: 1.12,
          p_adj_bv: '2.81',
          ind_p_adj_bv: '2.77',
          stock_status: 'Active',
          dt: '2024-07-19 15:31:00',
          vol: 672092,
          mcap: 1230081,
          roe: '',
          car: 16.8,
          roa: 1.68,
          net_sale: 0,
          sector_chgp: -0.65,
          index_label: 'SENSEX',
          '5D_avg_vol': 17765298,
          vol_chgp: -30.34,
          mcap_grade: '1',
          is_traded: 1,
          val_trd: 1084336430.5,
          wk_high52: 1791.9,
          wk_low52: 1363.45,
        },
        cover_page_data: {
          cover_headline: 'Strong </br>Long Term Fundamentals ',
          cover_summary: [
            {
              big_txt: 'Very Positive',
              small_txt: 'Results in Mar 24',
            },
            {
              big_txt: 'Mildly Bullish',
              small_txt: 'Technical Trend',
            },
            {
              big_txt: 'Fair',
              small_txt: 'Valuation',
            },
            {
              big_txt: ' High (82.65%)',
              small_txt: 'Institutional Holding',
            },
          ],
        },
        score_text: 'strong buy',
        cover_clr: 'coverhead-green',
        stock_details: {
          sid: 592009,
          sname: 'HDFC Bank Ltd.',
          short_name: 'HDFC Bank',
          scripcode: 500180,
          symbol: 'HDFCBANK',
          isin: 'INE040A01034',
          status: 'Active',
          ind_code: 50,
          ind_name: 'Private Banks',
          sublisting: 'Active',
          alias: 'HDFC Bank,HDFCBANK,HDFC Bank,INE040A01026,500180,HDFCBk',
          fincode: 100180,
          fv: 1,
          header_msg: '',
          mcap_type: 1,
          inc_mnth: '30-08',
          inc_yr: '1994',
          is_seasonal: 1,
          acc_ind_code: 15,
          acc_ind_name: 'Bank - Private',
          hse_code: 336,
          amfi_mcapsizerank: 'largecap',
          jan31_high_2018: {
            bse: 1005.95,
            nse: 1006.75,
          },
          updated_at: '2018-01-01',
          nsedt: '2024-07-18',
          bsedt: '2024-07-19',
        },
        link: null,
        exch: 0,
      },
      show_fallstock: 'no',
      stockList: undefined,
    },
  },

  // hdfc LIC report option
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 1,
        name: 'switcher',
        reason: 'not buy and strong buy',
      },
      sname: 'HDFC Life Insur.',
      qty: '',
      mcap: 147256.04609562,
      mcapclass: 'Large Cap',
      ind_name: 'Finance/NBFC',
      mcaptype: 1,
      ind_code: 5,
      ques: {
        list: [
          {
            q: 'Do you want to Switch to',
            opt: [
              {
                txt: 'Higher rated Stock in Finance/NBFC Sector',
                val: 's-343801',
                valsid: 343801,
                details: {
                  sid: 343801,
                  scoreText: 'Buy',
                  score: 78,
                  type: 's',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Manappuram Fin.',
                type: 's',
                other_choice: {
                  '112501': {
                    sid: 112501,
                    scoreText: 'Strong Buy',
                    score: 82,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'Axis Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,112501&oth=343801,264317&sh=s,a&scid=5,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '264317': {
                    sid: 264317,
                    scoreText: 'Strong Buy',
                    score: 81,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'BASF India',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,264317&oth=343801,112501&sh=s,m&scid=5,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,343801&oth=112501,264317&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock in Large Cap',
                val: 'm-112501',
                valsid: 112501,
                details: {
                  sid: 112501,
                  scoreText: 'Strong Buy',
                  score: 82,
                  type: 'a',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Axis Bank',
                type: 'm',
                other_choice: {
                  '343801': {
                    sid: 343801,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across Finance/NBFC sector',
                    type: 's',
                    short_name: 'Manappuram Fin.',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,343801&oth=112501,264317&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '264317': {
                    sid: 264317,
                    scoreText: 'Strong Buy',
                    score: 81,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'BASF India',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,264317&oth=112501,343801&sh=m,s&scid=1,5&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,112501&oth=343801,264317&sh=s,a&scid=5,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock across the Market',
                val: 'a-264317',
                valsid: 264317,
                details: {
                  sid: 264317,
                  scoreText: 'Strong Buy',
                  score: 81,
                  type: 'a',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'BASF India',
                type: 'a',
                other_choice: {
                  '343801': {
                    sid: 343801,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across Finance/NBFC sector',
                    type: 's',
                    short_name: 'Manappuram Fin.',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,343801&oth=264317,112501&sh=a,m&scid=,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '112501': {
                    sid: 112501,
                    scoreText: 'Strong Buy',
                    score: 82,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'Axis Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,112501&oth=264317,343801&sh=a,s&scid=,5&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=1002872,264317&oth=343801,112501&sh=s,m&scid=5,1&nos=,&othnos=,&downloadswitcher=1',
              },
            ],
          },
        ],
        show: 1,
        switch_chng: 0,
        switch_msg: 'YOU HAVE ENTERED',
      },
      show_fallstock: 'no',
    },
  },

  // basf india
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 2,
        name: 'verdict',
        reason: 'buy and strong buy',
      },
      sname: 'BASF India',
      qty: '',
      mcap: 27049.196436,
      mcapclass: 'Large Cap',
      ind_name: 'Pesticides & Agrochem',
      mcaptype: 1,
      ind_code: 18,
      verdict: {
        price_info: {
          cmp: 6249,
          open_price: 6189.95,
          day_low: 6056.85,
          day_high: 6344,
          '52wk_low_dt': '2023-10-25',
          '52wk_high_dt': '2024-07-26',
          altm_low: 63.5,
          altm_high: 6344,
          altm_low_dt: '2001-07-03',
          altm_high_dt: '2024-07-26',
          vol_msg: 'Compared to 5 day average volume of 76.18 k at 15:53 PM',
          mcap_class: 'Large Cap',
          bid_price: 6249,
          bid_qty: 10,
          offer_price: 6345,
          offer_qty: 1,
          no_of_shares: 43285640,
          div_yeild: 0.25,
          net_profit: 1614.3,
          pe_ratio: 46.8,
          ind_pe_ratio: 16.72,
          deb_equity: -0.15,
          price_to_book: 8.18,
          net_npa_perc: '',
          gross_npa_perc: '',
          p_adj_bv: '',
          ind_p_adj_bv: '',
          stock_status: 'Active',
          dt: '2024-07-31 16:01:00',
          vol: 2327,
          mcap: 27049.196436,
          roe: 17.48,
          car: '',
          roa: '',
          net_sale: 33599.7,
          sector_chgp: 0.98,
          index_label: 'SENSEX',
          '5D_avg_vol': 76181,
          vol_chgp: -74.89,
          mcap_grade: '1',
          is_traded: 1,
          val_trd: 14428388.975,
          wk_high52: 6344,
          wk_low52: 2421.35,
        },
        cover_page_data: {
          cover_headline: 'Low Debt   ',
          cover_summary: [
            {
              big_txt: 'Healthy Growth in',
              small_txt: 'Long Term Operating Profits',
            },
            {
              big_txt: 'Very Positive',
              small_txt: 'Results in Mar 24',
            },
            {
              big_txt: 'Bullish',
              small_txt: 'Technical Trend',
            },
            {
              big_txt: 'Fair',
              small_txt: 'Valuation',
            },
          ],
        },
        score_text: 'strong buy',
        cover_clr: 'coverhead-green',
        stock_details: {
          sid: 264317,
          sname: 'BASF India Ltd',
          short_name: 'BASF India',
          scripcode: 500042,
          symbol: 'BASF',
          isin: 'INE373A01013',
          status: 'Active',
          ind_code: 18,
          ind_name: 'Pesticides & Agrochem',
          sublisting: 'Active',
          alias: 'BASF India,BASF,BASF,INE373A01013,500042,BASFInd',
          fincode: 100042,
          fv: 10,
          header_msg: '',
          mcap_type: 1,
          inc_mnth: 'May',
          inc_yr: '1943',
          is_seasonal: 1,
          acc_ind_code: 2,
          acc_ind_name: 'Pesticides & Agrochemicals',
          hse_code: 371,
          amfi_mcapsizerank: 'smallcap',
          jan31_high_2018: {
            bse: 2159.7,
            nse: 2155.95,
          },
          updated_at: '2018-01-01',
          nsedt: '2024-07-30',
          bsedt: '2024-07-31',
        },
        link: null,
        exch: 0,
      },
      show_fallstock: 'no',
    },
  },

  // infosys normal
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 2,
        name: 'verdict',
        reason: 'buy and strong buy',
      },
      sname: 'Infosys',
      qty: '',
      mcap: 748279,
      mcapclass: 'Large Cap',
      ind_name: 'IT - Software ',
      mcaptype: 1,
      ind_code: 57,
      verdict: {
        price_info: {
          cmp: 1789.3,
          open_price: 1842.05,
          day_low: 1786,
          day_high: 1843,
          '52wk_low_dt': '2023-07-21',
          '52wk_high_dt': '2024-07-18',
          altm_low: 0.82,
          altm_high: 1953.7,
          altm_low_dt: '1995-05-03',
          altm_high_dt: '2022-01-17',
          vol_msg: 'Compared to 5 day average volume of 96.98 lacs at 15:25 PM',
          mcap_class: 'Large Cap',
          bid_price: 1788.9,
          bid_qty: 253,
          offer_price: 1790,
          offer_qty: 1445,
          no_of_shares: 4152028475,
          div_yeild: 2.61,
          net_profit: 63740,
          pe_ratio: 27.84,
          ind_pe_ratio: '35.26',
          deb_equity: -0.22,
          price_to_book: 8.29,
          net_npa_perc: '',
          gross_npa_perc: '',
          p_adj_bv: '0',
          ind_p_adj_bv: '8.52',
          stock_status: 'Active',
          dt: '2024-07-19 15:31:00',
          vol: 1647646,
          mcap: 748279,
          roe: 29.77,
          car: '',
          roa: '',
          net_sale: 393150,
          sector_chgp: -0.41,
          index_label: 'SENSEX',
          '5D_avg_vol': 9698187.4,
          vol_chgp: -19.13,
          mcap_grade: '1',
          is_traded: 1,
          val_trd: 2989653667,
          wk_high52: 1843,
          wk_low52: 1311.6,
        },
        cover_page_data: {
          cover_headline: 'Strong </br>Long Term Fundamentals ',
          cover_summary: [
            {
              big_txt: 'Positive',
              small_txt: 'Results in Jun 24',
            },
            {
              big_txt: 'Mildly Bullish',
              small_txt: 'Technical Trend',
            },
            {
              big_txt: 'Fair',
              small_txt: 'Valuation',
            },
            {
              big_txt: ' High (70.03%)',
              small_txt: 'Institutional Holding',
            },
          ],
        },
        score_text: 'buy',
        cover_clr: 'coverhead-green-light',
        stock_details: {
          sid: 399834,
          sname: 'Infosys Ltd.',
          short_name: 'Infosys',
          scripcode: 500209,
          symbol: 'INFY',
          isin: 'INE009A01021',
          status: 'Active',
          ind_code: 57,
          ind_name: 'IT - Software ',
          sublisting: 'Active',
          alias: 'Infosys,INFY,Infosys,INE009A01021,500209,Infy',
          fincode: 100209,
          fv: 5,
          header_msg: '',
          mcap_type: 1,
          inc_mnth: '02-07',
          inc_yr: '1981',
          is_seasonal: 0,
          acc_ind_code: 65,
          acc_ind_name: 'IT - Software ',
          hse_code: 206,
          amfi_mcapsizerank: 'largecap',
          jan31_high_2018: {
            bse: 583,
            nse: 583.3,
          },
          updated_at: '2018-01-01',
          nsedt: '2024-07-18',
          bsedt: '2024-07-19',
        },
        link: null,
        exch: 0,
      },
      show_fallstock: 'no',
    },
  },

  // infosys india
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 1,
        name: 'switcher',
        reason: 'not buy and strong buy',
      },
      sname: 'Info Edg.(India)',
      qty: '',
      mcap: 89696.1881106,
      mcapclass: 'Large Cap',
      ind_name: 'IT - Software ',
      mcaptype: 1,
      ind_code: 57,
      ques: {
        list: [
          {
            q: 'Do you want to Switch to',
            opt: [
              {
                txt: 'Higher rated Stock in IT - Software  Sector',
                val: 's-234277',
                valsid: 234277,
                details: {
                  sid: 234277,
                  scoreText: 'Buy',
                  score: 78,
                  type: 's',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Persistent Sys',
                type: 's',
                other_choice: {
                  '112501': {
                    sid: 112501,
                    scoreText: 'Strong Buy',
                    score: 82,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'Axis Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,112501&oth=234277,264317&sh=s,a&scid=57,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '264317': {
                    sid: 264317,
                    scoreText: 'Strong Buy',
                    score: 81,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'BASF India',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,264317&oth=234277,112501&sh=s,m&scid=57,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=112501,264317&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock in Large Cap',
                val: 'm-112501',
                valsid: 112501,
                details: {
                  sid: 112501,
                  scoreText: 'Strong Buy',
                  score: 82,
                  type: 'm',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Axis Bank',
                type: 'm',
                other_choice: {
                  '234277': {
                    sid: 234277,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across IT - Software  sector',
                    type: 's',
                    short_name: 'Persistent Sys',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=112501,264317&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '264317': {
                    sid: 264317,
                    scoreText: 'Strong Buy',
                    score: 81,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'BASF India',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,264317&oth=112501,234277&sh=m,s&scid=1,57&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,112501&oth=234277,264317&sh=s,a&scid=57,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock across the Market',
                val: 'a-264317',
                valsid: 264317,
                details: {
                  sid: 264317,
                  scoreText: 'Strong Buy',
                  score: 81,
                  type: 'a',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'BASF India',
                type: 'a',
                other_choice: {
                  '234277': {
                    sid: 234277,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across IT - Software  sector',
                    type: 's',
                    short_name: 'Persistent Sys',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=264317,112501&sh=a,m&scid=,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '112501': {
                    sid: 112501,
                    scoreText: 'Strong Buy',
                    score: 82,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'Axis Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,112501&oth=264317,234277&sh=a,s&scid=,57&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,264317&oth=234277,112501&sh=s,m&scid=57,1&nos=,&othnos=,&downloadswitcher=1',
              },
            ],
          },
        ],
        show: 1,
        switch_chng: 0,
        switch_msg: 'YOU HAVE ENTERED',
      },
      show_fallstock: 'no',
    },
  },

  // infosys Eco Recyc with options
  {
    code: '200',
    message: 'Success',
    data: {
      block_page: 0,
      remaining_views: 0,
      total_views: 0,
      ispaid: 1,
      islogin: true,
      sect_type: {
        id: 1,
        name: 'switcher',
        reason: 'not buy and strong buy',
      },
      sname: 'Eco Recyc.)',
      qty: '',
      mcap: 87747.6632634,
      mcapclass: 'Large Cap',
      ind_name: 'IT - Software ',
      mcaptype: 1,
      ind_code: 57,
      ques: {
        list: [
          {
            q: 'Do you want to Switch to',
            opt: [
              {
                txt: 'Higher rated Stock in IT - Software  Sector',
                val: 's-234277',
                valsid: 234277,
                details: {
                  sid: 234277,
                  scoreText: 'Buy',
                  score: 78,
                  type: 's',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Persistent Sys',
                type: 's',
                other_choice: {
                  '478299': {
                    sid: 478299,
                    scoreText: 'Strong Buy',
                    score: 84,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'ICICI Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,478299&oth=234277,972395&sh=s,a&scid=57,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '972395': {
                    sid: 972395,
                    scoreText: 'Strong Buy',
                    score: 84,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'Cholaman.Inv.&Fn',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,972395&oth=234277,478299&sh=s,m&scid=57,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=478299,972395&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock in Large Cap',
                val: 'm-478299',
                valsid: 478299,
                details: {
                  sid: 478299,
                  scoreText: 'Strong Buy',
                  score: 84,
                  type: 's',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'ICICI Bank',
                type: 'm',
                other_choice: {
                  '234277': {
                    sid: 234277,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across IT - Software  sector',
                    type: 's',
                    short_name: 'Persistent Sys',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=478299,972395&sh=m,a&scid=1,&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '972395': {
                    sid: 972395,
                    scoreText: 'Strong Buy',
                    score: 84,
                    heading: 'Across the Market',
                    type: 'a',
                    short_name: 'Cholaman.Inv.&Fn',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,972395&oth=478299,234277&sh=m,s&scid=1,57&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,478299&oth=234277,972395&sh=s,a&scid=57,&nos=,&othnos=,&downloadswitcher=1',
              },
              {
                txt: 'Higher rated Stock across the Market',
                val: 'a-972395',
                valsid: 972395,
                details: {
                  sid: 972395,
                  scoreText: 'Strong Buy',
                  score: 84,
                  type: 's',
                  short_name: '',
                  dw_url: '',
                },
                short_name: 'Cholaman.Inv.&Fn',
                type: 'a',
                other_choice: {
                  '234277': {
                    sid: 234277,
                    scoreText: 'Buy',
                    score: 78,
                    heading: 'Across IT - Software  sector',
                    type: 's',
                    short_name: 'Persistent Sys',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,234277&oth=972395,478299&sh=a,m&scid=,1&nos=,&othnos=,&downloadswitcher=1',
                  },
                  '478299': {
                    sid: 478299,
                    scoreText: 'Strong Buy',
                    score: 84,
                    heading: 'Across Large Cap',
                    type: 'm',
                    short_name: 'ICICI Bank',
                    dw_url:
                      '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,478299&oth=972395,234277&sh=a,s&scid=,57&nos=,&othnos=,&downloadswitcher=1',
                  },
                },
                dw_url:
                  '/Stocks_Stockresearchreport/getSwitcherDownload?sids=925707,972395&oth=234277,478299&sh=s,m&scid=57,1&nos=,&othnos=,&downloadswitcher=1',
              },
            ],
          },
        ],
        show: 1,
        switch_chng: 0,
        switch_msg: 'YOU HAVE ENTERED',
      },
      show_fallstock: 'no',
    },
  },

];
