import { IGetDropdown } from "../models/interfaces";

// Interface for each item in the sub-array
export const searchData: IGetDropdown[] = [
  {
    Id: 1003455,
    Company: 'Indian <b>Rail</b>way Finance Corporation Ltd',
    ScriptCode: '543257',
    Symbol: 'IRFC',
    url: 'https://www.marketsmojo.com/stocks-analysis/indian-railway-finance-corporation-1003455-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'I R F C',
    tag: 'Stock',
    stockprice: '205.30',
    chg: '1.65',
    chgp: '0.81',
    chgdir: 1,
    score: 58,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003455,
    Company: 'Indian <b>Rail</b>way Finance Corporation Ltd',
    ScriptCode: '543257',
    Symbol: 'IRFC',
    url: 'https://www.marketsmojo.com/news/indian-railway-finance-corporation-ltd-1003455',
    price: null,
    ExchangeName: 'bse',
    sname: 'I R F C',
    tag: 'News',
    stockprice: '205.30',
    chg: '1.65',
    chgp: '0.81',
    chgdir: 1,
    score: 58,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003127,
    Company: '<b>Rail</b> Vikas Nigam Ltd',
    ScriptCode: 542649,
    Symbol: 'RVNL',
    url: 'https://www.marketsmojo.com/stocks-analysis/rail-vikas-nigam-1003127-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Rail Vikas',
    tag: 'Stock',
    stockprice: '636.15',
    chg: '25.60',
    chgp: '4.19',
    chgdir: 1,
    score: 64,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003127,
    Company: '<b>Rail</b> Vikas Nigam Ltd',
    ScriptCode: 542649,
    Symbol: 'RVNL',
    url: 'https://www.marketsmojo.com/news/rail-vikas-nigam-ltd-1003127',
    price: null,
    ExchangeName: 'bse',
    sname: 'Rail Vikas',
    tag: 'News',
    stockprice: '636.15',
    chg: '25.60',
    chgp: '4.19',
    chgdir: 1,
    score: 64,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003280,
    Company: 'Indian <b>Rail</b>way Catering & Tourism Corporation Ltd',
    ScriptCode: 542830,
    Symbol: 'IRCTC',
    url: 'https://www.marketsmojo.com/stocks-analysis/indian-railway-catering-tourism-corporation-1003280-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'I R C T C',
    tag: 'Stock',
    stockprice: '1035.55',
    chg: '14.15',
    chgp: '1.39',
    chgdir: 1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003280,
    Company: 'Indian <b>Rail</b>way Catering & Tourism Corporation Ltd',
    ScriptCode: 542830,
    Symbol: 'IRCTC',
    url: 'https://www.marketsmojo.com/news/indian-railway-catering-tourism-corporation-ltd-1003280',
    price: null,
    ExchangeName: 'bse',
    sname: 'I R C T C',
    tag: 'News',
    stockprice: '1035.55',
    chg: '14.15',
    chgp: '1.39',
    chgdir: 1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003463,
    Company: '<b>Rail</b>tel Corporation of India Ltd',
    ScriptCode: 543265,
    Symbol: 'RAILTEL',
    url: 'https://www.marketsmojo.com/stocks-analysis/railtel-corporation-of-india-1003463-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Railtel Corpn.',
    tag: 'Stock',
    stockprice: '519.50',
    chg: '-2.10',
    chgp: '-0.40',
    chgdir: -1,
    score: 71,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003463,
    Company: '<b>Rail</b>tel Corporation of India Ltd',
    ScriptCode: 543265,
    Symbol: 'RAILTEL',
    url: 'https://www.marketsmojo.com/news/railtel-corporation-of-india-ltd-1003463',
    price: null,
    ExchangeName: 'bse',
    sname: 'Railtel Corpn.',
    tag: 'News',
    stockprice: '519.50',
    chg: '-2.10',
    chgp: '-0.40',
    chgdir: -1,
    score: 71,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 664903,
    Company: 'Texmaco <b>Rail</b> & Engineering Ltd',
    ScriptCode: 533326,
    Symbol: 'TEXRAIL',
    url: 'https://www.marketsmojo.com/stocks-analysis/texmaco-rail-engineering-664903-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Texmaco Rail',
    tag: 'Stock',
    stockprice: '284.65',
    chg: '10.00',
    chgp: '3.64',
    chgdir: 1,
    score: 61,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 664903,
    Company: 'Texmaco <b>Rail</b> & Engineering Ltd',
    ScriptCode: 533326,
    Symbol: 'TEXRAIL',
    url: 'https://www.marketsmojo.com/news/texmaco-rail-engineering-ltd-664903',
    price: null,
    ExchangeName: 'bse',
    sname: 'Texmaco Rail',
    tag: 'News',
    stockprice: '284.65',
    chg: '10.00',
    chgp: '3.64',
    chgdir: 1,
    score: 61,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 529147,
    Company: 'Oriental <b>Rail</b> Infrastructure Ltd',
    ScriptCode: 531859,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/oriental-rail-infrastructure-529147-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Oriental Rail',
    tag: 'Stock',
    stockprice: '378.55',
    chg: '18.00',
    chgp: '4.99',
    chgdir: 1,
    score: 75,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 529147,
    Company: 'Oriental <b>Rail</b> Infrastructure Ltd',
    ScriptCode: 531859,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/oriental-rail-infrastructure-ltd-529147',
    price: null,
    ExchangeName: 'bse',
    sname: 'Oriental Rail',
    tag: 'News',
    stockprice: '378.55',
    chg: '18.00',
    chgp: '4.99',
    chgdir: 1,
    score: 75,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 102257,
    Company: 'K&R <b>Rail</b> Engineering Ltd',
    ScriptCode: 514360,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/k-r-rail-engineering-102257-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'K&R Rail Engine.',
    tag: 'Stock',
    stockprice: '491.00',
    chg: '11.80',
    chgp: '2.46',
    chgdir: 1,
    score: 42,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 102257,
    Company: 'K&R <b>Rail</b> Engineering Ltd',
    ScriptCode: 514360,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/k-r-rail-engineering-ltd-102257',
    price: null,
    ExchangeName: 'bse',
    sname: 'K&R Rail Engine.',
    tag: 'News',
    stockprice: '491.00',
    chg: '11.80',
    chgp: '2.46',
    chgdir: 1,
    score: 42,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 919938,
    Company: 'NR Agarwal Industries Ltd. - N<b>RAIL</b>',
    ScriptCode: 516082,
    Symbol: 'NRAIL',
    url: 'https://www.marketsmojo.com/stocks-analysis/nr-agarwal-industries-919938-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'NR Agarwal Inds',
    tag: 'Stock',
    stockprice: '484.50',
    chg: '-10.45',
    chgp: '-2.11',
    chgdir: -1,
    score: 54,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 919938,
    Company: 'NR Agarwal Industries Ltd. - N<b>RAIL</b>',
    ScriptCode: 516082,
    Symbol: 'NRAIL',
    url: 'https://www.marketsmojo.com/news/nr-agarwal-industries-ltd-919938',
    price: null,
    ExchangeName: 'bse',
    sname: 'NR Agarwal Inds',
    tag: 'News',
    stockprice: '484.50',
    chg: '-10.45',
    chgp: '-2.11',
    chgdir: -1,
    score: 54,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 421449,
    Company: 'Cressanda <b>Rail</b>way Solutions Ltd',
    ScriptCode: 512379,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/cressanda-railway-solutions-421449-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Cressanda Railwa',
    tag: 'Stock',
    stockprice: '12.18',
    chg: '-0.26',
    chgp: '-2.09',
    chgdir: -1,
    score: 51,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 421449,
    Company: 'Cressanda <b>Rail</b>way Solutions Ltd',
    ScriptCode: 512379,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/cressanda-railway-solutions-ltd-421449',
    price: null,
    ExchangeName: 'bse',
    sname: 'Cressanda Railwa',
    tag: 'News',
    stockprice: '12.18',
    chg: '-0.26',
    chgp: '-2.09',
    chgdir: -1,
    score: 51,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003080,
    Company: 'BCPL <b>Rail</b>way Infrastructure Ltd',
    ScriptCode: 542057,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/bcpl-railway-infrastructure-1003080-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'BCPL Railway',
    tag: 'Stock',
    stockprice: '103.75',
    chg: '-2.10',
    chgp: '-1.98',
    chgdir: -1,
    score: 43,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003080,
    Company: 'BCPL <b>Rail</b>way Infrastructure Ltd',
    ScriptCode: 542057,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/bcpl-railway-infrastructure-ltd-1003080',
    price: null,
    ExchangeName: 'bse',
    sname: 'BCPL Railway',
    tag: 'News',
    stockprice: '103.75',
    chg: '-2.10',
    chgp: '-1.98',
    chgdir: -1,
    score: 43,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },

  {
    Id: 478299,
    Company: '<b>ICICI</b> Bank Ltd.',
    ScriptCode: 532174,
    Symbol: 'ICICIBANK',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-bank-478299-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Bank',
    tag: 'Stock',
    stockprice: '1230.00',
    chg: '-12.45',
    chgp: '-1.00',
    chgdir: -1,
    score: 84,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 478299,
    Company: '<b>ICICI</b> Bank Ltd.',
    ScriptCode: 532174,
    Symbol: 'ICICIBANK',
    url: 'https://www.marketsmojo.com/news/icici-bank-ltd-478299',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Bank',
    tag: 'News',
    stockprice: '1230.00',
    chg: '-12.45',
    chgp: '-1.00',
    chgdir: -1,
    score: 84,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002663,
    Company: '<b>ICICI</b> Prudential Life Insurance Company Ltd',
    ScriptCode: 540133,
    Symbol: 'ICICIPRULI',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-prudential-life-insurance-company-1002663-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Pru Life',
    tag: 'Stock',
    stockprice: '660.80',
    chg: '0.25',
    chgp: '0.04',
    chgdir: 1,
    score: 62,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002663,
    Company: '<b>ICICI</b> Prudential Life Insurance Company Ltd',
    ScriptCode: 540133,
    Symbol: 'ICICIPRULI',
    url: 'https://www.marketsmojo.com/news/icici-prudential-life-insurance-company-ltd-1002663',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Pru Life',
    tag: 'News',
    stockprice: '660.80',
    chg: '0.25',
    chgp: '0.04',
    chgdir: 1,
    score: 62,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002823,
    Company: '<b>ICICI</b> Lombard General Insurance Company Ltd',
    ScriptCode: 540716,
    Symbol: 'ICICIGI',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-lombard-general-insurance-company-1002823-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Lombard',
    tag: 'Stock',
    stockprice: '1880.00',
    chg: '0.35',
    chgp: '0.02',
    chgdir: 1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002823,
    Company: '<b>ICICI</b> Lombard General Insurance Company Ltd',
    ScriptCode: 540716,
    Symbol: 'ICICIGI',
    url: 'https://www.marketsmojo.com/news/icici-lombard-general-insurance-company-ltd-1002823',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Lombard',
    tag: 'News',
    stockprice: '1880.00',
    chg: '0.35',
    chgp: '0.02',
    chgdir: 1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002957,
    Company: '<b>ICICI</b> Securities Ltd',
    ScriptCode: 541179,
    Symbol: 'ISEC',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-securities-1002957-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Securities',
    tag: 'Stock',
    stockprice: '776.55',
    chg: '-2.85',
    chgp: '-0.37',
    chgdir: -1,
    score: 82,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002957,
    Company: '<b>ICICI</b> Securities Ltd',
    ScriptCode: 541179,
    Symbol: 'ISEC',
    url: 'https://www.marketsmojo.com/news/icici-securities-ltd-1002957',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Securities',
    tag: 'News',
    stockprice: '776.55',
    chg: '-2.85',
    chgp: '-0.37',
    chgdir: -1,
    score: 82,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 262956,
    Company: '<b>ICICI</b> Ltd (Merged)',
    ScriptCode: 500015,
    Symbol: 'ICICI',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-ltd-merged-262956-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI-Merged',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 262956,
    Company: '<b>ICICI</b> Ltd (Merged)',
    ScriptCode: 500015,
    Symbol: 'ICICI',
    url: 'https://www.marketsmojo.com/news/icici-ltd-merged--262956',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI-Merged',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1001449,
    Company: '<b>ICICI</b> Bank (PP) (Delisted)',
    ScriptCode: 890124,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/icici-bank-pp-1001449-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Bank (PP)',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1001449,
    Company: '<b>ICICI</b> Bank (PP) (Delisted)',
    ScriptCode: 890124,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/icici-bank-pp--1001449',
    price: null,
    ExchangeName: 'bse',
    sname: 'ICICI Bank (PP)',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 399834,
    Company: '<b>Infosys</b> Ltd.',
    ScriptCode: 500209,
    Symbol: 'INFY',
    url: 'https://www.marketsmojo.com/stocks-analysis/infosys-399834-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Infosys',
    tag: 'Stock',
    stockprice: '1651.70',
    chg: '4.00',
    chgp: '0.24',
    chgdir: 1,
    score: 70,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 399834,
    Company: '<b>Infosys</b> Ltd.',
    ScriptCode: 500209,
    Symbol: 'INFY',
    url: 'https://www.marketsmojo.com/news/infosys-ltd-399834',
    price: null,
    ExchangeName: 'bse',
    sname: 'Infosys',
    tag: 'News',
    stockprice: '1651.70',
    chg: '4.00',
    chgp: '0.24',
    chgdir: 1,
    score: 70,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 925707,
    Company: '<b>Info</b> Edge (India) Ltd',
    ScriptCode: 532777,
    Symbol: 'NAUKRI',
    url: 'https://www.marketsmojo.com/stocks-analysis/info-edge-india-925707-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Info Edg.(India)',
    tag: 'Stock',
    stockprice: '6932.55',
    chg: '31.55',
    chgp: '0.46',
    chgdir: 1,
    score: 64,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 896075,
    Company: 'Eco Recycling Ltd - <b>InfoSys</b>c',
    ScriptCode: 530643,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/eco-recycling-896075-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Eco Recyc.',
    tag: 'Stock',
    stockprice: '759.00',
    chg: '15.95',
    chgp: '2.15',
    chgdir: 1,
    score: 64,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 896075,
    Company: 'Eco Recycling Ltd - <b>InfoSys</b>c',
    ScriptCode: 530643,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/eco-recycling-ltd-896075',
    price: null,
    ExchangeName: 'bse',
    sname: 'Eco Recyc.',
    tag: 'News',
    stockprice: '759.00',
    chg: '15.95',
    chgp: '2.15',
    chgdir: 1,
    score: 64,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 386301,
    Company: 'HCL <b>Infosys</b>tems Ltd',
    ScriptCode: 500179,
    Symbol: 'HCL-INSYS',
    url: 'https://www.marketsmojo.com/stocks-analysis/hcl-infosystems-386301-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'HCL Infosystems',
    tag: 'Stock',
    stockprice: '16.50',
    chg: '-0.05',
    chgp: '-0.30',
    chgdir: -1,
    score: 12,
    scoretext: 'Strong Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 386301,
    Company: 'HCL <b>Infosys</b>tems Ltd',
    ScriptCode: 500179,
    Symbol: 'HCL-INSYS',
    url: 'https://www.marketsmojo.com/news/hcl-infosystems-ltd-386301',
    price: null,
    ExchangeName: 'bse',
    sname: 'HCL Infosystems',
    tag: 'News',
    stockprice: '16.50',
    chg: '-0.05',
    chgp: '-0.30',
    chgdir: -1,
    score: 12,
    scoretext: 'Strong Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 10039240,
    Company: 'Slone <b>Infosys</b>tems Ltd',
    ScriptCode: 92903,
    Symbol: 'SLONE',
    url: 'https://www.marketsmojo.com/stocks-analysis/slone-infosystems-10039240-1',
    price: null,
    ExchangeName: 'nse',
    sname: 'Slone',
    tag: 'Stock',
    stockprice: '156.00',
    chg: '-3.65',
    chgp: '-2.29',
    chgdir: -1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 10039240,
    Company: 'Slone <b>Infosys</b>tems Ltd',
    ScriptCode: 92903,
    Symbol: 'SLONE',
    url: 'https://www.marketsmojo.com/news/slone-infosystems-ltd-10039240',
    price: null,
    ExchangeName: 'nse',
    sname: 'Slone',
    tag: 'News',
    stockprice: '156.00',
    chg: '-3.65',
    chgp: '-2.29',
    chgdir: -1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002688,
    Company: 'Southern <b>Infosys</b> Ltd',
    ScriptCode: 540174,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/southern-infosys-1002688-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Southern Infosys',
    tag: 'Stock',
    stockprice: '26.03',
    chg: '1.23',
    chgp: '4.96',
    chgdir: 1,
    score: 57,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002688,
    Company: 'Southern <b>Infosys</b> Ltd',
    ScriptCode: 540174,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/southern-infosys-ltd-1002688',
    price: null,
    ExchangeName: 'bse',
    sname: 'Southern Infosys',
    tag: 'News',
    stockprice: '26.03',
    chg: '1.23',
    chgp: '4.96',
    chgdir: 1,
    score: 57,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 192803,
    Company: 'Shyama <b>Infosys</b> Ltd',
    ScriptCode: 531219,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/shyama-infosys-192803-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Shyama Infosys',
    tag: 'Stock',
    stockprice: '5.62',
    chg: '-0.28',
    chgp: '-4.75',
    chgdir: -1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 192803,
    Company: 'Shyama <b>Infosys</b> Ltd',
    ScriptCode: 531219,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/shyama-infosys-ltd-192803',
    price: null,
    ExchangeName: 'bse',
    sname: 'Shyama Infosys',
    tag: 'News',
    stockprice: '5.62',
    chg: '-0.28',
    chgp: '-4.75',
    chgdir: -1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 777263,
    Company: 'Palsoft <b>Infosys</b>tems Ltd (Delisted)',
    ScriptCode: 511597,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/palsoft-infosystems-777263-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Palsoft Infosys.',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 777263,
    Company: 'Palsoft <b>Infosys</b>tems Ltd (Delisted)',
    ScriptCode: 511597,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/palsoft-infosystems-ltd-777263',
    price: null,
    ExchangeName: 'bse',
    sname: 'Palsoft Infosys.',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 317876,
    Company: ' (Delisted) - Websity <b>Infosys</b>',
    ScriptCode: 511415,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/-317876-0',
    price: null,
    ExchangeName: 'bse',
    sname: null,
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: '',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 317876,
    Company: ' (Delisted) - Websity <b>Infosys</b>',
    ScriptCode: 511415,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/-317876',
    price: null,
    ExchangeName: 'bse',
    sname: null,
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: '',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 779494,
    Company: 'Diamond <b>Infosys</b>tems Ltd (Delisted)',
    ScriptCode: 530801,
    Symbol: '',
    url: 'https://www.marketsmojo.com/stocks-analysis/diamond-infosystems-779494-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Diamond Infosys.',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 779494,
    Company: 'Diamond <b>Infosys</b>tems Ltd (Delisted)',
    ScriptCode: 530801,
    Symbol: '',
    url: 'https://www.marketsmojo.com/news/diamond-infosystems-ltd-779494',
    price: null,
    ExchangeName: 'bse',
    sname: 'Diamond Infosys.',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 861770,
    Company: 'Compudyne W<b>infosys</b>tems Ltd (Delisted)',
    ScriptCode: 532306,
    Symbol: 'COMPUDYNE',
    url: 'https://www.marketsmojo.com/stocks-analysis/compudyne-winfosystems-861770-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Compudyne Win',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 861770,
    Company: 'Compudyne W<b>infosys</b>tems Ltd (Delisted)',
    ScriptCode: 532306,
    Symbol: 'COMPUDYNE',
    url: 'https://www.marketsmojo.com/news/compudyne-winfosystems-ltd-861770',
    price: null,
    ExchangeName: 'bse',
    sname: 'Compudyne Win',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 513374,
    Company: '<b>Tata</b> Consultancy Services Ltd.',
    ScriptCode: 532540,
    Symbol: 'TCS',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-consultancy-services-513374-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'TCS',
    tag: 'Stock',
    stockprice: '3912.20',
    chg: '2.30',
    chgp: '0.06',
    chgdir: 1,
    score: 75,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 513374,
    Company: '<b>Tata</b> Consultancy Services Ltd.',
    ScriptCode: 532540,
    Symbol: 'TCS',
    url: 'https://www.marketsmojo.com/news/tata-consultancy-services-ltd-513374',
    price: null,
    ExchangeName: 'bse',
    sname: 'TCS',
    tag: 'News',
    stockprice: '3912.20',
    chg: '2.30',
    chgp: '0.06',
    chgdir: 1,
    score: 75,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 949886,
    Company: '<b>Tata</b> Motors Ltd.',
    ScriptCode: 500570,
    Symbol: 'TATAMOTORS',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-motors-949886-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Motors',
    tag: 'Stock',
    stockprice: '1021.60',
    chg: '16.15',
    chgp: '1.61',
    chgdir: 1,
    score: 78,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 949886,
    Company: '<b>Tata</b> Motors Ltd.',
    ScriptCode: 500570,
    Symbol: 'TATAMOTORS',
    url: 'https://www.marketsmojo.com/news/tata-motors-ltd-949886',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Motors',
    tag: 'News',
    stockprice: '1021.60',
    chg: '16.15',
    chgp: '1.61',
    chgdir: 1,
    score: 78,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 594470,
    Company: '<b>Tata</b> Steel Ltd',
    ScriptCode: 500470,
    Symbol: 'TATASTEEL',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-steel-594470-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Steel',
    tag: 'Stock',
    stockprice: '169.90',
    chg: '1.90',
    chgp: '1.13',
    chgdir: 1,
    score: 61,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 594470,
    Company: '<b>Tata</b> Steel Ltd',
    ScriptCode: 500470,
    Symbol: 'TATASTEEL',
    url: 'https://www.marketsmojo.com/news/tata-steel-ltd-594470',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Steel',
    tag: 'News',
    stockprice: '169.90',
    chg: '1.90',
    chgp: '1.13',
    chgdir: 1,
    score: 61,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 790869,
    Company: '<b>Tata</b> Power Company Ltd',
    ScriptCode: 500400,
    Symbol: 'TATAPOWER',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-power-company-790869-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Power Co.',
    tag: 'Stock',
    stockprice: '441.35',
    chg: '4.10',
    chgp: '0.94',
    chgdir: 1,
    score: 58,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 790869,
    Company: '<b>Tata</b> Power Company Ltd',
    ScriptCode: 500400,
    Symbol: 'TATAPOWER',
    url: 'https://www.marketsmojo.com/news/tata-power-company-ltd-790869',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Power Co.',
    tag: 'News',
    stockprice: '441.35',
    chg: '4.10',
    chgp: '0.94',
    chgdir: 1,
    score: 58,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 272806,
    Company: '<b>Tata</b> Consumer Products Ltd',
    ScriptCode: 500800,
    Symbol: 'TATACONSUM',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-consumer-products-272806-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Consumer',
    tag: 'Stock',
    stockprice: '1142.40',
    chg: '-8.85',
    chgp: '-0.77',
    chgdir: -1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 272806,
    Company: '<b>Tata</b> Consumer Products Ltd',
    ScriptCode: 500800,
    Symbol: 'TATACONSUM',
    url: 'https://www.marketsmojo.com/news/tata-consumer-products-ltd-272806',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Consumer',
    tag: 'News',
    stockprice: '1142.40',
    chg: '-8.85',
    chgp: '-0.77',
    chgdir: -1,
    score: 72,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 952728,
    Company: '<b>Tata</b> Communications Ltd',
    ScriptCode: 500483,
    Symbol: 'TATACOMM',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-communications-952728-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Comm',
    tag: 'Stock',
    stockprice: '1851.15',
    chg: '-3.25',
    chgp: '-0.18',
    chgdir: -1,
    score: 36,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 952728,
    Company: '<b>Tata</b> Communications Ltd',
    ScriptCode: 500483,
    Symbol: 'TATACOMM',
    url: 'https://www.marketsmojo.com/news/tata-communications-ltd-952728',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Comm',
    tag: 'News',
    stockprice: '1851.15',
    chg: '-3.25',
    chgp: '-0.18',
    chgdir: -1,
    score: 36,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 949649,
    Company: '<b>Tata</b> Elxsi Ltd.',
    ScriptCode: '500408',
    Symbol: 'TATAELXSI',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-elxsi-949649-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Elxsi',
    tag: 'Stock',
    stockprice: '6984.00',
    chg: '-134.80',
    chgp: '-1.89',
    chgdir: -1,
    score: 42,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 949649,
    Company: '<b>Tata</b> Elxsi Ltd.',
    ScriptCode: '500408',
    Symbol: 'TATAELXSI',
    url: 'https://www.marketsmojo.com/news/tata-elxsi-ltd-949649',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Elxsi',
    tag: 'News',
    stockprice: '6984.00',
    chg: '-134.80',
    chgp: '-1.89',
    chgdir: -1,
    score: 42,
    scoretext: 'Sell',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 10039079,
    Company: '<b>Tata</b> Technologies Ltd',
    ScriptCode: '544028',
    Symbol: 'TATATECH',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-technologies-10039079-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Technolog.',
    tag: 'Stock',
    stockprice: '1013.85',
    chg: '2.75',
    chgp: '0.27',
    chgdir: 1,
    score: 55,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 10039079,
    Company: '<b>Tata</b> Technologies Ltd',
    ScriptCode: '544028',
    Symbol: 'TATATECH',
    url: 'https://www.marketsmojo.com/news/tata-technologies-ltd-10039079',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Technolog.',
    tag: 'News',
    stockprice: '1013.85',
    chg: '2.75',
    chgp: '0.27',
    chgdir: 1,
    score: 55,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 302622,
    Company: '<b>Tata</b> Motors - DVR Ordinary',
    ScriptCode: 570001,
    Symbol: 'TATAMTRDVR',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-motors-dvr-ordinary-302622-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Motors - DVR',
    tag: 'Stock',
    stockprice: '694.00',
    chg: '10.95',
    chgp: '1.60',
    chgdir: 1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 302622,
    Company: '<b>Tata</b> Motors - DVR Ordinary',
    ScriptCode: 570001,
    Symbol: 'TATAMTRDVR',
    url: 'https://www.marketsmojo.com/news/tata-motors-dvr-ordinary-302622',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Motors - DVR',
    tag: 'News',
    stockprice: '694.00',
    chg: '10.95',
    chgp: '1.60',
    chgdir: 1,
    score: '',
    scoretext: 'Not Rated',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 371122,
    Company: '<b>Tata</b> Investment Corporation Ltd',
    ScriptCode: 501301,
    Symbol: 'TATAINVEST',
    url: 'https://www.marketsmojo.com/stocks-analysis/tata-investment-corporation-371122-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Inv.Corpn.',
    tag: 'Stock',
    stockprice: '6421.05',
    chg: '-20.95',
    chgp: '-0.33',
    chgdir: -1,
    score: 62,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 371122,
    Company: '<b>Tata</b> Investment Corporation Ltd',
    ScriptCode: 501301,
    Symbol: 'TATAINVEST',
    url: 'https://www.marketsmojo.com/news/tata-investment-corporation-ltd-371122',
    price: null,
    ExchangeName: 'bse',
    sname: 'Tata Inv.Corpn.',
    tag: 'News',
    stockprice: '6421.05',
    chg: '-20.95',
    chgp: '-0.33',
    chgdir: -1,
    score: 62,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 592009,
    Company: '<b>HDFC</b> Bank Ltd.',
    ScriptCode: 500180,
    Symbol: 'HDFCBANK',
    url: 'https://www.marketsmojo.com/stocks-analysis/hdfc-bank-592009-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC Bank',
    tag: 'Stock',
    stockprice: '1608.50',
    chg: '-17.75',
    chgp: '-1.09',
    chgdir: -1,
    score: 88,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 592009,
    Company: '<b>HDFC</b> Bank Ltd.',
    ScriptCode: 500180,
    Symbol: 'HDFCBANK',
    url: 'https://www.marketsmojo.com/news/hdfc-bank-ltd-592009',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC Bank',
    tag: 'News',
    stockprice: '1608.50',
    chg: '-17.75',
    chgp: '-1.09',
    chgdir: -1,
    score: 88,
    scoretext: 'Strong Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002872,
    Company: '<b>HDFC</b> Life Insurance Company Ltd',
    ScriptCode: 540777,
    Symbol: 'HDFCLIFE',
    url: 'https://www.marketsmojo.com/stocks-analysis/hdfc-life-insurance-company-1002872-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC Life Insur.',
    tag: 'Stock',
    stockprice: '635.50',
    chg: '2.85',
    chgp: '0.45',
    chgdir: 1,
    score: 51,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1002872,
    Company: '<b>HDFC</b> Life Insurance Company Ltd',
    ScriptCode: 540777,
    Symbol: 'HDFCLIFE',
    url: 'https://www.marketsmojo.com/news/hdfc-life-insurance-company-ltd-1002872',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC Life Insur.',
    tag: 'News',
    stockprice: '635.50',
    chg: '2.85',
    chgp: '0.45',
    chgdir: 1,
    score: 51,
    scoretext: 'Hold',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003028,
    Company: '<b>HDFC</b> Asset Management Company Ltd',
    ScriptCode: '541729',
    Symbol: 'HDFCAMC',
    url: 'https://www.marketsmojo.com/stocks-analysis/hdfc-asset-management-company-1003028-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC AMC',
    tag: 'Stock',
    stockprice: '4156.85',
    chg: '10.05',
    chgp: '0.24',
    chgdir: 1,
    score: 78,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 1003028,
    Company: '<b>HDFC</b> Asset Management Company Ltd',
    ScriptCode: '541729',
    Symbol: 'HDFCAMC',
    url: 'https://www.marketsmojo.com/news/hdfc-asset-management-company-ltd-1003028',
    price: null,
    ExchangeName: 'bse',
    sname: 'HDFC AMC',
    tag: 'News',
    stockprice: '4156.85',
    chg: '10.05',
    chgp: '0.24',
    chgdir: 1,
    score: 78,
    scoretext: 'Buy',
    stock_traded_status: 'Active',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 741664,
    Company: 'Housing Development Finance CorporationLtd(Merged) - <b>HDFC</b>',
    ScriptCode: 500010,
    Symbol: 'HDFC',
    url: 'https://www.marketsmojo.com/stocks-analysis/housing-development-finance-corporationltdmerged-741664-0',
    price: null,
    ExchangeName: 'bse',
    sname: 'H D F C',
    tag: 'Stock',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
  {
    Id: 741664,
    Company: 'Housing Development Finance CorporationLtd(Merged) - <b>HDFC</b>',
    ScriptCode: 500010,
    Symbol: 'HDFC',
    url: 'https://www.marketsmojo.com/news/housing-development-finance-corporationltd-merged--741664',
    price: null,
    ExchangeName: 'bse',
    sname: 'H D F C',
    tag: 'News',
    stockprice: '',
    chg: '',
    chgp: '',
    chgdir: '',
    score: '',
    scoretext: '',
    stock_traded_status: 'Not Traded',
    show_score: 1,
    recurl: '',
  },
];
